<Project Sdk="Cosmos.Sdk/3.0.77">

  <PropertyGroup>
    <CosmosKernelClass>Windose.Kernel</CosmosKernelClass>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Fonts\spleen-12x24.psfu" />
    <None Remove="Resources\Fonts\spleen-16x32.psfu" />
    <None Remove="Resources\Fonts\spleen-32x64.psfu" />
    <None Remove="Resources\Fonts\spleen-5x8.psfu" />
    <None Remove="Resources\Fonts\spleen-6x12.psfu" />
    <None Remove="Resources\Fonts\spleen-8x16.psfu" />
    <None Remove="Resources\Wallpapers\Lithium.jpg" />
    <None Remove="Resources\Wallpapers\Lithium.png" />
  </ItemGroup>

  <!-- Core kernel packages -->
  <ItemGroup>
    <PackageReference Include="Cosmos.Kernel" Version="3.0.77" />
    <PackageReference Include="Cosmos.Kernel.System" Version="3.0.77" />
  </ItemGroup>

    <ItemGroup>
    <EmbeddedResource Include=".\Resources\Fonts\ARIAL.TTF" />
    <EmbeddedResource Include=".\Resources\Cursors\arrow.png" />
    <EmbeddedResource Include=".\Resources\Fonts\spleen-12x24.psfu" />
    <EmbeddedResource Include=".\Resources\Fonts\spleen-16x32.psfu" />
    <EmbeddedResource Include=".\Resources\Fonts\spleen-32x64.psfu" />
    <EmbeddedResource Include=".\Resources\Fonts\spleen-5x8.psfu" />
    <EmbeddedResource Include=".\Resources\Fonts\spleen-6x12.psfu" />
    <EmbeddedResource Include=".\Resources\Fonts\spleen-8x16.psfu" />
    <EmbeddedResource Include="Resources\Wallpapers\Lithium.png" />
  </ItemGroup>

</Project>
