<Project Sdk="Cosmos.Sdk/3.0.82">

  <PropertyGroup>
    <CosmosKernelClass>Windose.Kernel</CosmosKernelClass>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    
  </PropertyGroup>

  <!-- Core kernel packages -->
  <ItemGroup>
    <PackageReference Include="Cosmos.Kernel" Version="3.0.82" />
    <PackageReference Include="Cosmos.Kernel.System" Version="3.0.82" />
    <PackageReference Include="HtmlAgilityPack" Version="1.13.0" />
  </ItemGroup>

    <ItemGroup>
    <EmbeddedResource Include=".\Resources\Fonts\ARIAL.TTF" />
    <EmbeddedResource Include=".\Resources\Cursors\arrow.png" />
    <EmbeddedResource Include=".\Resources\Fonts\spleen-12x24.psfu" />
    <EmbeddedResource Include=".\Resources\Fonts\spleen-16x32.psfu" />
    <EmbeddedResource Include=".\Resources\Fonts\spleen-32x64.psfu" />
    <EmbeddedResource Include=".\Resources\Fonts\spleen-5x8.psfu" />
    <EmbeddedResource Include=".\Resources\Fonts\spleen-6x12.psfu" />
    <EmbeddedResource Include=".\Resources\Fonts\spleen-8x16.psfu" />
    <EmbeddedResource Include=".\Resources\Icons\appwizard.png" />
    <EmbeddedResource Include=".\Resources\Icons\console_prompt.png" />
    <EmbeddedResource Include=".\Resources\Icons\directory_closed.png" />
    <EmbeddedResource Include=".\Resources\Icons\display_properties.png" />
    <EmbeddedResource Include=".\Resources\Icons\executable_gear.png" />
    <EmbeddedResource Include=".\Resources\Icons\file_windows.png" />
    <EmbeddedResource Include=".\Resources\Icons\font_tt.png" />
    <EmbeddedResource Include=".\Resources\Wallpapers\Lithium.png" />
    <EmbeddedResource Include=".\Resources\Icons\accessibility.png" />
    <EmbeddedResource Include=".\Resources\Icons\ac_plug.png" />
    <EmbeddedResource Include=".\Resources\Icons\amplify.png" />
    <EmbeddedResource Include=".\Resources\Icons\application_hammer_grouppol.png" />
    <EmbeddedResource Include=".\Resources\Icons\application_hourglass.png" />
    <EmbeddedResource Include=".\Resources\Icons\appwiz_file.png" />
    <EmbeddedResource Include=".\Resources\Icons\cable.png" />
    <EmbeddedResource Include=".\Resources\Icons\calculator.png" />
    <EmbeddedResource Include=".\Resources\Icons\calendar.png" />
    <EmbeddedResource Include=".\Resources\Icons\cd_drive_purple5.png" />
    <EmbeddedResource Include=".\Resources\Icons\charmap.png" />
    <EmbeddedResource Include=".\Resources\Icons\chart.png" />
    <EmbeddedResource Include=".\Resources\Icons\check.png" />
    <EmbeddedResource Include=".\Resources\Icons\chip_ramdrive.png" />
    <EmbeddedResource Include=".\Resources\Icons\chm.png" />
    <EmbeddedResource Include=".\Resources\Icons\circle_question.png" />
    <EmbeddedResource Include=".\Resources\Icons\clean_drive.png" />
    <EmbeddedResource Include=".\Resources\Icons\clock.png" />
    <EmbeddedResource Include=".\Resources\Icons\computermona.png" />
    <EmbeddedResource Include=".\Resources\Icons\computerwil.png" />
    <EmbeddedResource Include=".\Resources\Icons\computer_gear.png" />
    <EmbeddedResource Include=".\Resources\Icons\computer_padlock.png" />
    <EmbeddedResource Include=".\Resources\Icons\computer_search.png" />
    <EmbeddedResource Include=".\Resources\Icons\computer_sound.png" />
    <EmbeddedResource Include=".\Resources\Icons\computer_taskmgr.png" />
    <EmbeddedResource Include=".\Resources\Icons\computer_user_pencil.png" />
    <EmbeddedResource Include=".\Resources\Icons\conn_cloud.png" />
    <EmbeddedResource Include=".\Resources\Icons\defragment.png" />
    <EmbeddedResource Include=".\Resources\Icons\desktop.png" />
    <EmbeddedResource Include=".\Resources\Icons\directory_explorer.png" />
    <EmbeddedResource Include=".\Resources\Icons\directory_folder_options.png" />
    <EmbeddedResource Include=".\Resources\Icons\directory_fonts.png" />
    <EmbeddedResource Include=".\Resources\Icons\directory_network_conn.png" />
    <EmbeddedResource Include=".\Resources\Icons\directory_open_file_mydocs.png" />
    <EmbeddedResource Include=".\Resources\Icons\directx.png" />
    <EmbeddedResource Include=".\Resources\Icons\document.png" />
    <EmbeddedResource Include=".\Resources\Icons\eject_pc.png" />
    <EmbeddedResource Include=".\Resources\Icons\eject_pc_shell.png" />
    <EmbeddedResource Include=".\Resources\Icons\erase_file.png" />
    <EmbeddedResource Include=".\Resources\Icons\event_log.png" />
    <EmbeddedResource Include=".\Resources\Icons\executable.png" />
    <EmbeddedResource Include=".\Resources\Icons\executable_script.png" />
    <EmbeddedResource Include=".\Resources\Icons\expand_hierarchial_array.png" />
    <EmbeddedResource Include=".\Resources\Icons\expansion_board.png" />
    <EmbeddedResource Include=".\Resources\Icons\filepack.png" />
    <EmbeddedResource Include=".\Resources\Icons\file_cd.png" />
    <EmbeddedResource Include=".\Resources\Icons\file_eye.png" />
    <EmbeddedResource Include=".\Resources\Icons\file_gears.png" />
    <EmbeddedResource Include=".\Resources\Icons\file_lines.png" />
    <EmbeddedResource Include=".\Resources\Icons\file_padlock.png" />
    <EmbeddedResource Include=".\Resources\Icons\file_program_group.png" />
    <EmbeddedResource Include=".\Resources\Icons\file_question.png" />
    <EmbeddedResource Include=".\Resources\Icons\file_set.png" />
    <EmbeddedResource Include=".\Resources\Icons\file_sorted_lock.png" />
    <EmbeddedResource Include=".\Resources\Icons\floppy_drive__55.png" />
    <EmbeddedResource Include=".\Resources\Icons\font_bitmap.png" />
    <EmbeddedResource Include=".\Resources\Icons\font_opentype.png" />
    <EmbeddedResource Include=".\Resources\Icons\font_tt_green.png" />
    <EmbeddedResource Include=".\Resources\Icons\frame_web.png" />
    <EmbeddedResource Include=".\Resources\Icons\gears_tweakui_a.png" />
    <EmbeddedResource Include=".\Resources\Icons\globe_map5.png" />
    <EmbeddedResource Include=".\Resources\Icons\hardware.png" />
    <EmbeddedResource Include=".\Resources\Icons\hard_disk_drive.png" />
    <EmbeddedResource Include=".\Resources\Icons\hard_disk_drive_pie.png" />
    <EmbeddedResource Include=".\Resources\Icons\hard_disk_drive_tools.png" />
    <EmbeddedResource Include=".\Resources\Icons\help_question_mark.png" />
    <EmbeddedResource Include=".\Resources\Icons\help_sheet.png" />
    <EmbeddedResource Include=".\Resources\Icons\history.png" />
    <EmbeddedResource Include=".\Resources\Icons\homepage_alt.png" />
    <EmbeddedResource Include=".\Resources\Icons\html.png" />
    <EmbeddedResource Include=".\Resources\Icons\html_new.png" />
    <EmbeddedResource Include=".\Resources\Icons\imagwmf.png" />
    <EmbeddedResource Include=".\Resources\Icons\input_devices-3.png" />
    <EmbeddedResource Include=".\Resources\Icons\input_devices.png" />
    <EmbeddedResource Include=".\Resources\Icons\installer_file_gear.png" />
    <EmbeddedResource Include=".\Resources\Icons\installer_generic_old.png" />
    <EmbeddedResource Include=".\Resources\Icons\internet_connection_wiz.png" />
    <EmbeddedResource Include=".\Resources\Icons\internet_options.png" />
    <EmbeddedResource Include=".\Resources\Icons\internet_options_old_e.png" />
    <EmbeddedResource Include=".\Resources\Icons\java.png" />
    <EmbeddedResource Include=".\Resources\Icons\java_dpf.png" />
    <EmbeddedResource Include=".\Resources\Icons\java_ocx.png" />
    <EmbeddedResource Include=".\Resources\Icons\joystick_alt.png" />
    <EmbeddedResource Include=".\Resources\Icons\keyboard.png" />
    <EmbeddedResource Include=".\Resources\Icons\keyboard_delay.png" />
    <EmbeddedResource Include=".\Resources\Icons\keyboard_repeat_rate.png" />
    <EmbeddedResource Include=".\Resources\Icons\loudspeaker_muted.png" />
    <EmbeddedResource Include=".\Resources\Icons\loudspeaker_rays.png" />
    <EmbeddedResource Include=".\Resources\Icons\loudspeaker_wave.png" />
    <EmbeddedResource Include=".\Resources\Icons\magnifying_glass.png" />
    <EmbeddedResource Include=".\Resources\Icons\mailbox_world.png" />
    <EmbeddedResource Include=".\Resources\Icons\mci_devices.png" />
    <EmbeddedResource Include=".\Resources\Icons\media_player.png" />
    <EmbeddedResource Include=".\Resources\Icons\media_player_file.png" />
    <EmbeddedResource Include=".\Resources\Icons\memory.png" />
    <EmbeddedResource Include=".\Resources\Icons\message_envelope_open.png" />
    <EmbeddedResource Include=".\Resources\Icons\message_file.png" />
    <EmbeddedResource Include=".\Resources\Icons\mixer_sound.png" />
    <EmbeddedResource Include=".\Resources\Icons\modem.png" />
    <EmbeddedResource Include=".\Resources\Icons\monitor_application.png" />
    <EmbeddedResource Include=".\Resources\Icons\monitor_black.png" />
    <EmbeddedResource Include=".\Resources\Icons\monitor_blue_grad.png" />
    <EmbeddedResource Include=".\Resources\Icons\monitor_gear.png" />
    <EmbeddedResource Include=".\Resources\Icons\monitor_moon.png" />
    <EmbeddedResource Include=".\Resources\Icons\monitor_windows.png" />
    <EmbeddedResource Include=".\Resources\Icons\mouse_ms.png" />
    <EmbeddedResource Include=".\Resources\Icons\mouse_speed.png" />
    <EmbeddedResource Include=".\Resources\Icons\move_system_file.png" />
    <EmbeddedResource Include=".\Resources\Icons\msconfig.png" />
    <EmbeddedResource Include=".\Resources\Icons\msg_error.png" />
    <EmbeddedResource Include=".\Resources\Icons\msg_information.png" />
    <EmbeddedResource Include=".\Resources\Icons\msg_question.png" />
    <EmbeddedResource Include=".\Resources\Icons\msg_warning.png" />
    <EmbeddedResource Include=".\Resources\Icons\msie.png" />
    <EmbeddedResource Include=".\Resources\Icons\msie_box.png" />
    <EmbeddedResource Include=".\Resources\Icons\msinfo.png" />
    <EmbeddedResource Include=".\Resources\Icons\msn.png" />
    <EmbeddedResource Include=".\Resources\Icons\msn3-3.png" />
    <EmbeddedResource Include=".\Resources\Icons\ms_dos.png" />
    <EmbeddedResource Include=".\Resources\Icons\multimedia.png" />
    <EmbeddedResource Include=".\Resources\Icons\network_drive.png" />
    <EmbeddedResource Include=".\Resources\Icons\network_drive_unavailable.png" />
    <EmbeddedResource Include=".\Resources\Icons\network_drive_world.png" />
    <EmbeddedResource Include=".\Resources\Icons\network_normal_two_pcs.png" />
    <EmbeddedResource Include=".\Resources\Icons\no.png" />
    <EmbeddedResource Include=".\Resources\Icons\notepad_file.png" />
    <EmbeddedResource Include=".\Resources\Icons\notepad_file_gear.png" />
    <EmbeddedResource Include=".\Resources\Icons\odbc.png" />
    <EmbeddedResource Include=".\Resources\Icons\overlay_refresh.png" />
    <EmbeddedResource Include=".\Resources\Icons\overlay_share.png" />
    <EmbeddedResource Include=".\Resources\Icons\overlay_shortcut.png" />
    <EmbeddedResource Include=".\Resources\Icons\package.png" />
    <EmbeddedResource Include=".\Resources\Icons\paint_file.png" />
    <EmbeddedResource Include=".\Resources\Icons\paint_old.png" />
    <EmbeddedResource Include=".\Resources\Icons\processor.png" />
    <EmbeddedResource Include=".\Resources\Icons\program_manager.png" />
    <EmbeddedResource Include=".\Resources\Icons\ram_drive.png" />
    <EmbeddedResource Include=".\Resources\Icons\recycle_bin_directory.png" />
    <EmbeddedResource Include=".\Resources\Icons\recycle_bin_empty.png" />
    <EmbeddedResource Include=".\Resources\Icons\recycle_bin_file.png" />
    <EmbeddedResource Include=".\Resources\Icons\recycle_bin_file_directory.png" />
    <EmbeddedResource Include=".\Resources\Icons\recycle_bin_full.png" />
    <EmbeddedResource Include=".\Resources\Icons\regedit_binary.png" />
    <EmbeddedResource Include=".\Resources\Icons\regedit_binary_lock.png" />
    <EmbeddedResource Include=".\Resources\Icons\regedit_file.png" />
    <EmbeddedResource Include=".\Resources\Icons\removable_disk_drive_alt.png" />
    <EmbeddedResource Include=".\Resources\Icons\rename.png" />
    <EmbeddedResource Include=".\Resources\Icons\replace_directory.png" />
    <EmbeddedResource Include=".\Resources\Icons\replace_file.png" />
    <EmbeddedResource Include=".\Resources\Icons\restrict.png" />
    <EmbeddedResource Include=".\Resources\Icons\scandisk.png" />
    <EmbeddedResource Include=".\Resources\Icons\scanregw.png" />
    <EmbeddedResource Include=".\Resources\Icons\script_file_blue.png" />
    <EmbeddedResource Include=".\Resources\Icons\scsi.png" />
    <EmbeddedResource Include=".\Resources\Icons\search_computer.png" />
    <EmbeddedResource Include=".\Resources\Icons\search_directory.png" />
    <EmbeddedResource Include=".\Resources\Icons\search_file.png" />
    <EmbeddedResource Include=".\Resources\Icons\search_laptop.png" />
    <EmbeddedResource Include=".\Resources\Icons\server_gear.png" />
    <EmbeddedResource Include=".\Resources\Icons\server_to_desktop.png" />
    <EmbeddedResource Include=".\Resources\Icons\server_window.png" />
    <EmbeddedResource Include=".\Resources\Icons\settings_gear.png" />
    <EmbeddedResource Include=".\Resources\Icons\shell_window.png" />
    <EmbeddedResource Include=".\Resources\Icons\shell_window3.png" />
    <EmbeddedResource Include=".\Resources\Icons\shut_down_normal.png" />
    <EmbeddedResource Include=".\Resources\Icons\sndvol_main.png" />
    <EmbeddedResource Include=".\Resources\Icons\standby_monitor_moon.png" />
    <EmbeddedResource Include=".\Resources\Icons\start_menu_shortcuts.png" />
    <EmbeddedResource Include=".\Resources\Icons\start_menu_xp.png" />
    <EmbeddedResource Include=".\Resources\Icons\system_restore.png" />
    <EmbeddedResource Include=".\Resources\Icons\telephony.png" />
    <EmbeddedResource Include=".\Resources\Icons\themes.png" />
    <EmbeddedResource Include=".\Resources\Icons\time_and_date.png" />
    <EmbeddedResource Include=".\Resources\Icons\tip.png" />
    <EmbeddedResource Include=".\Resources\Icons\true_type_paint.png" />
    <EmbeddedResource Include=".\Resources\Icons\trust.png" />
    <EmbeddedResource Include=".\Resources\Icons\trust_restrict.png" />
    <EmbeddedResource Include=".\Resources\Icons\unplug_storage.png" />
    <EmbeddedResource Include=".\Resources\Icons\url2-0.png" />
    <EmbeddedResource Include=".\Resources\Icons\users.png" />
    <EmbeddedResource Include=".\Resources\Icons\users_key.png" />
    <EmbeddedResource Include=".\Resources\Icons\user_computer_pair.png" />
    <EmbeddedResource Include=".\Resources\Icons\user_network.png" />
    <EmbeddedResource Include=".\Resources\Icons\user_world.png" />
    <EmbeddedResource Include=".\Resources\Icons\video.png" />
    <EmbeddedResource Include=".\Resources\Icons\winrep.png" />
    <EmbeddedResource Include=".\Resources\Icons\winrep_mag_glass.png" />
    <EmbeddedResource Include=".\Resources\Icons\world.png" />
    <EmbeddedResource Include=".\Resources\Icons\write_file.png" />
    <EmbeddedResource Include=".\Resources\Icons\write_red.png" />
    <EmbeddedResource Include=".\Resources\Icons\write_wordpad.png" />
    <EmbeddedResource Include=".\Resources\Icons\xml_gear.png" />
    <EmbeddedResource Include=".\Resources\Fonts\lucida-10x16.psf" />
    <EmbeddedResource Include=".\Resources\Wallpapers\WRAMW.png" />
  </ItemGroup>

    <ItemGroup>
      <Folder Include="System\Libs\" />
    </ItemGroup>

</Project>
